/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gudangbudi;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
/**
 *
 * @author HP
 */
public class menuregistrasi extends javax.swing.JFrame {
private DefaultTableModel model=null;
private PreparedStatement stat;
private ResultSet rs;
koneksi k = new koneksi();
    /**
     * Creates new form menuregistrasi
     */
    public menuregistrasi() {
        initComponents();
        k.connect ();
        refreshTable();
    }
      class user extends menuregistrasi{
        int id_user,level;
        String username,password;
        
        public user(){
          username = textusername.getText();
          password= textpass.getText();
          level = Integer.parseInt(boxlevel.getSelectedItem().toString());
        }
    }
       public void refreshTable() { 
model=new DefaultTableModel(); 
model.addColumn("Id_user"); 
model.addColumn("username"); 
model.addColumn("password"); 
model.addColumn("level");
tablereg.setModel(model); 
try {
this.stat=k.getcon().prepareStatement("select * from barang"); 
this.rs=this.stat.executeQuery();
while(rs.next()) { 
Object[] data={ rs.getInt("id_user"), 
rs.getString("username"),
rs.getString("password"),
rs.getInt("level"), 
}; 
model.addRow (data);
}
}catch (Exception e) { 
        JOptionPane.showMessageDialog(null,e.getMessage());
        } 

textiduser.setText(""); 
textusername.setText("");
textpass.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logoutregistrasi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textiduser = new javax.swing.JTextField();
        textusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textpass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        boxlevel = new javax.swing.JComboBox<>();
        tombolinput = new javax.swing.JButton();
        tombolupdate = new javax.swing.JButton();
        tombolbarang = new javax.swing.JButton();
        tombolbarangmasuk = new javax.swing.JButton();
        tombolbarangkeluar = new javax.swing.JButton();
        tomboldelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablereg = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText("Menu Registrasi");

        logoutregistrasi.setText("logout");
        logoutregistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutregistrasiActionPerformed(evt);
            }
        });

        jLabel2.setText("id user");

        jLabel3.setText("username");

        jLabel4.setText("password");

        textpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpassActionPerformed(evt);
            }
        });

        jLabel5.setText("level");

        boxlevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        tombolinput.setText("input");
        tombolinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolinputActionPerformed(evt);
            }
        });

        tombolupdate.setText("update");
        tombolupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolupdateActionPerformed(evt);
            }
        });

        tombolbarang.setText("barang");
        tombolbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbarangActionPerformed(evt);
            }
        });

        tombolbarangmasuk.setText("barang masuk");
        tombolbarangmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbarangmasukActionPerformed(evt);
            }
        });

        tombolbarangkeluar.setText("barang keluar");
        tombolbarangkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbarangkeluarActionPerformed(evt);
            }
        });

        tomboldelete.setText("delete");
        tomboldelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboldeleteActionPerformed(evt);
            }
        });

        tablereg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablereg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutregistrasi))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textusername, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(textiduser))
                .addGap(234, 234, 234))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(boxlevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(textpass, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(tombolbarangmasuk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tombolbarangkeluar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(tombolinput)
                                .addGap(33, 33, 33)
                                .addComponent(tombolupdate)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tombolbarang)
                            .addComponent(tomboldelete)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(textiduser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logoutregistrasi)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textusername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textpass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(boxlevel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolinput)
                    .addComponent(tombolupdate)
                    .addComponent(tombolbarang))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolbarangmasuk)
                    .addComponent(tombolbarangkeluar)
                    .addComponent(tomboldelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpassActionPerformed

    private void logoutregistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutregistrasiActionPerformed
        // TODO add your handling code here:
        login l = new login ();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutregistrasiActionPerformed

    private void tombolinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolinputActionPerformed
try {
            user b = new user();
            this.stat = k.getcon().prepareStatement("Insert into user values(?,?,?,?)");
            stat.setInt(1, 0);
            stat.setString(2, b.username);
            stat.setString(3, b.password);
            stat.setInt(4, b.level);
            stat.executeUpdate();
            refreshTable();
    } catch (Exception e) {
    JOptionPane.showMessageDialog(null, e.getMessage());
        }
                                                // TODO add your handling code here:
    }//GEN-LAST:event_tombolinputActionPerformed

    private void tombolupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolupdateActionPerformed
        // TODO add your handling code here:
            try {
           user u = new user ();
           this. stat = k.getcon().prepareStatement("update user set username=?,"+"password=? where id_user");
stat.setString(1, u.username);   
stat.setString(2, u.password); 
stat.setInt(3, u.level); 
stat.setString(4, textiduser.getText()); 
stat.executeUpdate(); 
refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tombolupdateActionPerformed

    private void tomboldeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboldeleteActionPerformed
        // TODO add your handling code here:
        try {
            this.stat = k.getcon().prepareStatement("delete from barang where id_user=?");
            stat.setInt(1, Integer.parseInt(textiduser.getText()));
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tomboldeleteActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
textiduser.setText(model.getValueAt(tablereg.getSelectedRow(),0).toString());
 textusername.setText(model.getValueAt(tablereg.getSelectedRow(),1).toString());
 textpass.setText(model.getValueAt(tablereg.getSelectedRow(),2).toString());
    }//GEN-LAST:event_formMouseClicked

    private void tombolbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbarangActionPerformed
        // TODO add your handling code here:
        tambahandatabarang bar = new tambahandatabarang();
        bar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolbarangActionPerformed

    private void tombolbarangmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbarangmasukActionPerformed
        // TODO add your handling code here:
        tambahbm barm = new tambahbm();
        barm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolbarangmasukActionPerformed

    private void tombolbarangkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbarangkeluarActionPerformed
        // TODO add your handling code here:
        tambahdatabk bark = new tambahdatabk();
        bark.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolbarangkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuregistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuregistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuregistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuregistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuregistrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxlevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutregistrasi;
    private javax.swing.JTable tablereg;
    private javax.swing.JTextField textiduser;
    private javax.swing.JTextField textpass;
    private javax.swing.JTextField textusername;
    private javax.swing.JButton tombolbarang;
    private javax.swing.JButton tombolbarangkeluar;
    private javax.swing.JButton tombolbarangmasuk;
    private javax.swing.JButton tomboldelete;
    private javax.swing.JButton tombolinput;
    private javax.swing.JButton tombolupdate;
    // End of variables declaration//GEN-END:variables

}
