/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gudangbudi;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class tambahbm extends javax.swing.JFrame {
  private DefaultTableModel model=null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();
    private int id_barang;
    private int jumlah;
    private String tanggal_masuk;
    /**
     * Creates new form tambahbm
     */
    public tambahbm() {
        initComponents();
            k.connect();
        refreshTable();
        refreshCombo();
    } public void refreshTable(){
        model = new DefaultTableModel();
        model.addColumn("id_barang_masuk");
        model.addColumn("id_barang");
        model.addColumn("jumlah");
        model.addColumn("tanggal");
        tablebm.setModel(model);
        try {
            this.stat = k.getcon().prepareStatement ("select * from barang_masuk ");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
                Object[] data={
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)
                };
                model.addRow(data); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        textidbm.setText("");
        textjumlahbm.setText("");
    }
        public void refreshCombo(){
            try {
                    this.stat = k.getcon().prepareStatement("select * from barang ");
                    this.rs = this.stat.executeQuery();
                   while (rs.next()) {
                       boxidbarang.addItem(rs.getString("id_barang")+":"+
                       rs.getString("nama_barang")+":"+rs.getString("stok"));
                   }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tombolbarang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textidbm = new javax.swing.JTextField();
        textjumlahbm = new javax.swing.JTextField();
        texttanggalbm = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablebm = new javax.swing.JTable();
        tombolinputbk = new javax.swing.JButton();
        tomnolupdate = new javax.swing.JButton();
        tomboldelete = new javax.swing.JButton();
        tombolbarang1 = new javax.swing.JButton();
        tombolbk = new javax.swing.JButton();
        boxidbarang = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tombolbarang.setText("barang");
        tombolbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbarangActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("tambah list data barang masuk");

        jLabel2.setText("id_barang_masuk");

        jLabel3.setText("id barang");

        jLabel4.setText("jumlah");

        jLabel5.setText("tanggal_barang");

        textidbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidbmActionPerformed(evt);
            }
        });

        jButton1.setText("loguot");

        tablebm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablebm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablebmMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablebm);

        tombolinputbk.setText("input");
        tombolinputbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolinputbkActionPerformed(evt);
            }
        });

        tomnolupdate.setText("update");
        tomnolupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomnolupdateActionPerformed(evt);
            }
        });

        tomboldelete.setText("delete");
        tomboldelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboldeleteActionPerformed(evt);
            }
        });

        tombolbarang1.setText("barang");
        tombolbarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbarang1ActionPerformed(evt);
            }
        });

        tombolbk.setText("barang keluar");
        tombolbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbkActionPerformed(evt);
            }
        });

        boxidbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxidbarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textidbm)
                            .addComponent(textjumlahbm)
                            .addComponent(texttanggalbm, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(boxidbarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tombolinputbk)
                        .addGap(18, 18, 18)
                        .addComponent(tomnolupdate)
                        .addGap(18, 18, 18)
                        .addComponent(tomboldelete)
                        .addGap(18, 18, 18)
                        .addComponent(tombolbarang1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolbk))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textidbm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(boxidbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textjumlahbm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(texttanggalbm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolinputbk)
                    .addComponent(tomnolupdate)
                    .addComponent(tomboldelete)
                    .addComponent(tombolbarang1))
                .addGap(18, 18, 18)
                .addComponent(tombolbk)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolinputbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolinputbkActionPerformed
        // TODO add your handling code here: try {
            try {
                tambahbm b = new tambahbm();
                this.stat = k.getcon().prepareStatement("Insert into barang_masuk values(?,?,?,?)");
                stat.setInt(1, 0);
                stat.setInt(2, b.id_barang);
                stat.setInt(3, b.jumlah);
                stat.setString(4, b.tanggal_masuk);
                stat.executeUpdate();
                refreshTable();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
    }//GEN-LAST:event_tombolinputbkActionPerformed
    }
    private void tomnolupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomnolupdateActionPerformed
        // TODO add your handling code here:
        try {
            tambahbm b = new tambahbm();
            this.stat = k.getcon().prepareStatement("update barang-masuk set id_barang_masuk=?,"+"jumlah=?,tanggal=? where id_barang_masuk=?");
            stat.setInt(1, b.id_barang);
            stat.setInt(2, b.jumlah);
            stat.setString(3, b.tanggal_masuk);
            stat.setString(4, textidbm.getText());
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }//GEN-LAST:event_tomnolupdateActionPerformed
    }
    private void tomboldeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboldeleteActionPerformed
        // TODO add your handling code here:
        try {
            tambahbm barm = new  tambahbm();
            this.stat = k.getcon().prepareStatement("delete from brg_masuk where id_bm=?");
            stat.setString(1, textidbm.getText());
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tomboldeleteActionPerformed

    private void tombolbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbarangActionPerformed
        // TODO add your handling code here:
        tambahandatabarang reg = new tambahandatabarang();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolbarangActionPerformed

    private void tombolbarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbarang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolbarang1ActionPerformed

    private void tombolbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbkActionPerformed
        // TODO add your handling code here:
        tambahbk reg = new tambahbk();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolbkActionPerformed

    private void textidbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidbmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidbmActionPerformed

    private void tablebmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablebmMouseClicked
        // TODO add your handling code here:
        textidbm.setText(model.getValueAt(tablebm.getSelectedRow(), 0).toString());
        textjumlahbm.setText(model.getValueAt(tablebm.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tablebmMouseClicked

    private void boxidbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxidbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxidbarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahbm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahbm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahbm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahbm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahbm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxidbarang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablebm;
    private javax.swing.JTextField textidbm;
    private javax.swing.JTextField textjumlahbm;
    private com.toedter.calendar.JDateChooser texttanggalbm;
    private javax.swing.JButton tombolbarang;
    private javax.swing.JButton tombolbarang1;
    private javax.swing.JButton tombolbk;
    private javax.swing.JButton tomboldelete;
    private javax.swing.JButton tombolinputbk;
    private javax.swing.JButton tomnolupdate;
    // End of variables declaration//GEN-END:variables

    
}
