/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gudangbudi;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class tambahbk extends javax.swing.JFrame {
    private DefaultTableModel model=null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();
    private int id_barang;
    private int jumlah;
    private String tanggal_keluar;
    /**
     * Creates new form tambahbk
     */
    public tambahbk() {
        initComponents();
        k.connect();
        refreshTable();
        refreshCombo();
    }
        public void refreshTable(){
        model = new DefaultTableModel();
        model.addColumn("id_barang_keluar");
        model.addColumn("id_barang");
        model.addColumn("jumlah");
        model.addColumn("tanggal");
        tablebk.setModel(model);
        try {
            this.stat = k.getcon().prepareStatement ("select * from barang_keluar ");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
                Object[] data={
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)
                };
                model.addRow(data); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        textidbk.setText("");
        textjumlahbk.setText("");
    }
        public void refreshCombo(){
            try {
                    this.stat = k.getcon().prepareStatement("select * from barang ");
                    this.rs = this.stat.executeQuery();
                   while (rs.next()) {
                       boxidbarang.addItem(rs.getString("id_barang")+":"+
                       rs.getString("nama_barang")+":"+rs.getString("stok"));
                   }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        logoutbk = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textidbk = new javax.swing.JTextField();
        textjumlahbk = new javax.swing.JTextField();
        texttanggalbk = new com.toedter.calendar.JDateChooser();
        tombolinputbk = new javax.swing.JButton();
        tomnolupdate = new javax.swing.JButton();
        tomboldelete = new javax.swing.JButton();
        tombolbarang = new javax.swing.JButton();
        tombolbm = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablebk = new javax.swing.JTable();
        boxidbarang = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("tambah list data barang keluar");

        logoutbk.setText("logout");
        logoutbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbkActionPerformed(evt);
            }
        });

        jLabel2.setText("id barang");

        jLabel3.setText("id barang keluar");

        jLabel4.setText("jumlah");

        jLabel5.setText("tanggal");

        textidbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidbkActionPerformed(evt);
            }
        });

        tombolinputbk.setText("input");
        tombolinputbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolinputbkActionPerformed(evt);
            }
        });

        tomnolupdate.setText("update");
        tomnolupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomnolupdateActionPerformed(evt);
            }
        });

        tomboldelete.setText("delete");
        tomboldelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboldeleteActionPerformed(evt);
            }
        });

        tombolbarang.setText("barang");
        tombolbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbarangActionPerformed(evt);
            }
        });

        tombolbm.setText("barang masuk");
        tombolbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbmActionPerformed(evt);
            }
        });

        tablebk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablebk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablebkMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablebk);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(logoutbk))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(texttanggalbk, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(textidbk, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(boxidbarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(textjumlahbk, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombolbm)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tombolinputbk)
                        .addGap(18, 18, 18)
                        .addComponent(tomnolupdate)
                        .addGap(18, 18, 18)
                        .addComponent(tomboldelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tombolbarang)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutbk)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(textidbk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(boxidbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(textjumlahbk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(texttanggalbk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tombolinputbk)
                            .addComponent(tomnolupdate)
                            .addComponent(tomboldelete)
                            .addComponent(tombolbarang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tombolbm)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolinputbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolinputbkActionPerformed
        // TODO add your handling code here: try {
        try {
        tambahbk b = new tambahbk();
            this.stat = k.getcon().prepareStatement("Insert into barang_keluar values(?,?,?,?)");
            stat.setInt(1, 0);
            stat.setInt(2, b.id_barang);
            stat.setInt(3, b.jumlah);
            stat.setString(4, b.tanggal_keluar);
            stat.executeUpdate();
            refreshTable();
    } catch (Exception e) {
    JOptionPane.showMessageDialog(null, e.getMessage());
    }//GEN-LAST:event_tombolinputbkActionPerformed
    }
    private void textidbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidbkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidbkActionPerformed

    private void tomnolupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomnolupdateActionPerformed
        // TODO add your handling code here:
           try {
        tambahbk b = new tambahbk();
            this.stat = k.getcon().prepareStatement("update barang-keluar set id_barang_keluar=?,"+"jumlah=?,tanggal=? where id_barang_keluar=?");
            stat.setInt(1, b.id_barang);
            stat.setInt(2, b.jumlah);
            stat.setString(3, b.tanggal_keluar);
            stat.setString(4, textidbk.getText());
            stat.executeUpdate();
            refreshTable();
    } catch (Exception e) {
    JOptionPane.showMessageDialog(null, e.getMessage());
    }//GEN-LAST:event_tomnolupdateActionPerformed
    }
    private void tomboldeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboldeleteActionPerformed
        // TODO add your handling code here:
        try {
             tambahbk bark = new  tambahbk();
            this.stat = k.getcon().prepareStatement("delete from brg_keluar where id_bk=?");
            stat.setString(1, textidbk.getText());
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tomboldeleteActionPerformed

    private void tombolbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbarangActionPerformed
        // TODO add your handling code here:
        tambahandatabarang reg = new tambahandatabarang();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolbarangActionPerformed

    private void tombolbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbmActionPerformed
        // TODO add your handling code here:
        tambahbm reg = new tambahbm();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolbmActionPerformed

    private void tablebkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablebkMouseClicked
        // TODO add your handling code here:
        textidbk.setText(model.getValueAt(tablebk.getSelectedRow(), 0).toString());
        textjumlahbk.setText(model.getValueAt(tablebk.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tablebkMouseClicked

    private void logoutbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbkActionPerformed
        // TODO add your handling code here:
         login l = new login ();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutbkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahbk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahbk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahbk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahbk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahbk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxidbarang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutbk;
    private javax.swing.JTable tablebk;
    private javax.swing.JTextField textidbk;
    private javax.swing.JTextField textjumlahbk;
    private com.toedter.calendar.JDateChooser texttanggalbk;
    private javax.swing.JButton tombolbarang;
    private javax.swing.JButton tombolbm;
    private javax.swing.JButton tomboldelete;
    private javax.swing.JButton tombolinputbk;
    private javax.swing.JButton tomnolupdate;
    // End of variables declaration//GEN-END:variables

   
}
